# Generated by Django 5.0.5 on 2024-05-21 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='-')),
                ('userID', models.TextField(default='-')),
                ('pwd', models.TextField(default='-')),
                ('Birthdate', models.DateField()),
                ('Gender', models.BooleanField(default=True)),
                ('Height', models.FloatField(default=0)),
                ('Weight', models.FloatField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
