# Generated by Django 5.0.5 on 2024-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Birthdate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pwd',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institutionID',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userpwd',
            field=models.TextField(default='-'),
        ),
    ]
